function [xdot, rotor_state_next, forces, vi, vi_qs, tau_s] = VTOL_RESPONSE_STEP(t, x, rotor_state, control_delta, fixed_control_delta, varargin)
%VTOL_RESPONSE_STEP One nonlinear response step for Simulink-style use.
%
% Inputs:
%   t                  time, s
%   x                  12x1 [u v w p q r phi theta psi x y z]
%   rotor_state         stacked rotor states. Blade model uses
%                       [beta(1:Nb); dbeta(1:Nb); vi]. Disk model uses
%                       [beta0 beta1c beta1s dbeta0 dbeta1c dbeta1s vi].
%   control_delta       4x1 rotor-control increments, deg
%   fixed_control_delta 3x1 [elevator rudder aileron] increments, deg
%   rotor_tilt_angle_deg optional 6x1 absolute nacelle tilt angles, deg
%   dt                 Simulink sample time for rotor-state update, s
%   sim_model          struct generated by RUN_RESPONSE_SIMULINK_SETUP
%
% Outputs:
%   xdot               aircraft state derivative
%   rotor_state_next   updated stacked rotor state
%   forces             6x1 total body force/moment
%   vi                 6x1 current induced velocities
%   vi_qs              6x1 quasi-steady induced velocities
%   tau_s              6x1 dynamic inflow time constants

if numel(varargin) == 2
    dt = varargin{1};
    sim_model = varargin{2};
    rotor_tilt_angles = sim_model.rotor_tilt_angles(:);
elseif numel(varargin) == 3
    rotor_tilt_angles = varargin{1};
    dt = varargin{2};
    sim_model = varargin{3};
else
    error('VTOL_RESPONSE_STEP:BadInputCount', ...
        'Use VTOL_RESPONSE_STEP(t,x,rotor_state,control_delta,fixed_control_delta,dt,sim_model) or include rotor_tilt_angle_deg before dt.');
end

rotor_controls = sim_model.control_trim.rotor(:) + control_delta(:);
fixed_controls = sim_model.control_trim.fixed(:) + fixed_control_delta(:);
rotor_tilt_angles = rotor_tilt_angles(:);
if numel(rotor_tilt_angles) ~= numel(sim_model.rotor_tilt_angles)
    error('VTOL_RESPONSE_STEP:BadRotorTiltInput', ...
        'rotor_tilt_angle_deg must contain %d values.', numel(sim_model.rotor_tilt_angles));
end
[rotor_controls, fixed_controls] = response_effective_control_channels_step( ...
    rotor_controls, fixed_controls, x, rotor_tilt_angles, sim_model);
rotor_states = unstack_rotor_state(rotor_state, sim_model);

[forces, rotor_states_next, inflow] = response_total_forces_step(x, rotor_states, rotor_controls, fixed_controls, rotor_tilt_angles, sim_model, dt);
xdot = response_aircraft_rhs_step(x, forces, sim_model);
rotor_state_next = stack_rotor_state(rotor_states_next);
vi = inflow.vi(:);
vi_qs = inflow.vi_qs(:);
tau_s = inflow.tau_s(:);

% Keep t referenced for Simulink diagnostics without changing behavior.
if ~isfinite(t)
    error('VTOL_RESPONSE_STEP:BadTime', 'Time input must be finite.');
end
end

function rotor_states = unstack_rotor_state(rotor_state, sim_model)
n_rotors = sim_model.n_rotors;
rotor_state_size = sim_model.rotor_state_size;
rotor_state = rotor_state(:);
if numel(rotor_state) ~= n_rotors * rotor_state_size
    error('VTOL_RESPONSE_STEP:BadRotorState', ...
        'rotor_state must contain %d values.', n_rotors * rotor_state_size);
end
rotor_states = cell(1, n_rotors);
for rotor_number = 1:n_rotors
    idx = (rotor_number-1)*rotor_state_size + (1:rotor_state_size);
    rotor_states{rotor_number} = rotor_state(idx);
end
end

function stacked = stack_rotor_state(rotor_states)
n_rotors = numel(rotor_states);
rotor_state_size = numel(rotor_states{1});
stacked = zeros(n_rotors * rotor_state_size, 1);
for rotor_number = 1:n_rotors
    idx = (rotor_number-1)*rotor_state_size + (1:rotor_state_size);
    stacked(idx) = rotor_states{rotor_number}(:);
end
end

function dx = response_aircraft_rhs_step(x, forces, sim_model)
u = x(1); v = x(2); w = x(3);
p = x(4); q = x(5); r = x(6);
phi = x(7); theta = x(8); psi = x(9);

mass = sim_model.mass_kg;
Ixx = sim_model.inertia_kg_m2(1);
Iyy = sim_model.inertia_kg_m2(2);
Izz = sim_model.inertia_kg_m2(3);
g = sim_model.gravity_m_s2;

dx = zeros(12,1);
dx(1) = forces(1)/mass - q*w + r*v - g*sin(theta);
dx(2) = forces(2)/mass - r*u + p*w + g*sin(phi)*cos(theta);
dx(3) = forces(3)/mass - p*v + q*u + g*cos(phi)*cos(theta);
dx(4) = (forces(4) + (Iyy - Izz)*q*r) / Ixx;
dx(5) = (forces(5) + (Izz - Ixx)*p*r) / Iyy;
dx(6) = (forces(6) + (Ixx - Iyy)*p*q) / Izz;

cth = cos(theta);
if abs(cth) < 1e-6
    if cth >= 0
        cth = 1e-6;
    else
        cth = -1e-6;
    end
end
dx(7) = p + tan(theta) * (q*sin(phi) + r*cos(phi));
dx(8) = q*cos(phi) - r*sin(phi);
dx(9) = (q*sin(phi) + r*cos(phi)) / cth;

C_b2e = body_to_earth_matrix_step(phi, theta, psi);
dx(10:12) = C_b2e * [u; v; w];
end

function [total_forces, next_rotor_states, inflow_info] = response_total_forces_step(x, rotor_states, rotor_controls, fixed_controls, rotor_tilt_angles, sim_model, state_dt_s)
velo_body = x(1:3);
angular_velocity = x(4:6);
acceleration = zeros(3,1);
angular_acc = zeros(3,1);

theta_vec = response_control_allocation_step(rotor_controls);
n_rotors = numel(rotor_states);
rotor_forces = zeros(6, n_rotors);
next_rotor_states = rotor_states;
inflow_info.vi = zeros(1, n_rotors);
inflow_info.vi_qs = zeros(1, n_rotors);
inflow_info.tau_s = zeros(1, n_rotors);

use_parallel_rotors = false;
if isfield(sim_model, 'use_parallel_rotors')
    use_parallel_rotors = logical(sim_model.use_parallel_rotors);
end

if use_parallel_rotors
    vi_tmp = zeros(1, n_rotors);
    vi_qs_tmp = zeros(1, n_rotors);
    tau_tmp = zeros(1, n_rotors);
    next_tmp = cell(1, n_rotors);
    parfor rotor_number = 1:n_rotors
        [forces_j, state_next, vi_current, vi_qs, tau_s] = response_one_rotor_step( ...
            rotor_number, rotor_states{rotor_number}, theta_vec, rotor_tilt_angles, ...
            velo_body, angular_velocity, acceleration, angular_acc, sim_model, state_dt_s);
        rotor_forces(:, rotor_number) = forces_j(:);
        next_tmp{rotor_number} = state_next;
        vi_tmp(rotor_number) = vi_current;
        vi_qs_tmp(rotor_number) = vi_qs;
        tau_tmp(rotor_number) = tau_s;
    end
    next_rotor_states = next_tmp;
    inflow_info.vi = vi_tmp;
    inflow_info.vi_qs = vi_qs_tmp;
    inflow_info.tau_s = tau_tmp;
else
    for rotor_number = 1:n_rotors
        [forces_j, state_next, vi_current, vi_qs, tau_s] = response_one_rotor_step( ...
            rotor_number, rotor_states{rotor_number}, theta_vec, rotor_tilt_angles, ...
            velo_body, angular_velocity, acceleration, angular_acc, sim_model, state_dt_s);
        rotor_forces(:, rotor_number) = forces_j(:);
        next_rotor_states{rotor_number} = state_next;
        inflow_info.vi(rotor_number) = vi_current;
        inflow_info.vi_qs(rotor_number) = vi_qs;
        inflow_info.tau_s(rotor_number) = tau_s;
    end
end

fuse_forces = response_fuselage_forces_step(fixed_controls, velo_body, angular_velocity, sim_model);
total_forces = sum(rotor_forces, 2) + fuse_forces(:);
end

function [forces_j, state_next, vi_current, vi_qs, tau_s] = response_one_rotor_step(rotor_number, rotor_state, theta_vec, rotor_tilt_angles, velo_body, angular_velocity, acceleration, angular_acc, sim_model, state_dt_s)
rotor_bemt_options = sim_model.rotor_bemt_options;
if response_flap_model_id_step(sim_model) == 2
    rotor_bemt_options.disk_state_dt_s = state_dt_s;
    if isfield(sim_model, 'disk_state_integrator')
        rotor_bemt_options.disk_state_integrator = sim_model.disk_state_integrator;
    end
    if isfield(sim_model, 'disk_state_substeps')
        rotor_bemt_options.disk_state_substeps = sim_model.disk_state_substeps;
    end
end

if isfield(sim_model, 'force_fun')
    [~, forces_j, beta_vals_j, dbeta_vals_j] = sim_model.force_fun(rotor_state, ...
        sim_model.R, sim_model.Nb, sim_model.omega, sim_model.I_beta, velo_body, sim_model.k_beta, ...
        sim_model.rotor_profile, theta_vec(rotor_number), rotor_tilt_angles(rotor_number), ...
        angular_velocity, sim_model.rotational_direction(rotor_number), acceleration, angular_acc, ...
        rotor_bemt_options, sim_model.rotor_locations{rotor_number});
else
    [~, forces_j, beta_vals_j, dbeta_vals_j] = response_rotor_force_eval_step(rotor_state, ...
        sim_model.R, sim_model.Nb, sim_model.omega, sim_model.I_beta, velo_body, sim_model.k_beta, ...
        sim_model.rotor_profile, theta_vec(rotor_number), rotor_tilt_angles(rotor_number), ...
        angular_velocity, sim_model.rotational_direction(rotor_number), acceleration, angular_acc, ...
        rotor_bemt_options, sim_model.rotor_locations{rotor_number}, response_flap_model_id_step(sim_model));
end

state_next = response_update_flap_state(rotor_state, beta_vals_j, dbeta_vals_j, sim_model);

vi_current = rotor_state(end);
[vi_qs, tau_s] = response_uniform_inflow_target_step(forces_j, velo_body, angular_velocity, rotor_tilt_angles, sim_model, rotor_number, vi_current);
if state_dt_s > 0 && response_inflow_model_id_step(sim_model.rotor_bemt_options) == 1
    state_next(end) = vi_qs + (vi_current - vi_qs) * exp(-state_dt_s / tau_s);
end
end

function state_next = response_update_flap_state(state_current, beta_vals, dbeta_vals, sim_model)
state_next = state_current;
switch response_flap_model_id_step(sim_model)
    case 1
        state_next(1:sim_model.Nb) = beta_vals(end,:).';
        state_next(sim_model.Nb+1:2*sim_model.Nb) = dbeta_vals(end,:).';
    case 2
        switch response_disk_update_id_step(sim_model)
            case 1
                state_next(1:3) = beta_vals(end,:).';
                state_next(4:6) = dbeta_vals(end,:).';
            case 2
                % Diagnostic option only. Dynamic is the normal response path.
            otherwise
                error('VTOL_RESPONSE_STEP:BadDiskFlapStateUpdate', ...
                    'sim_model.disk_flap_state_update must be "frozen" or "dynamic".');
        end
    otherwise
        error('VTOL_RESPONSE_STEP:BadFlapModel', ...
            'sim_model.flap_model must be "blade" or "disk".');
end
end

function model_id = response_flap_model_id_step(sim_model)
if isfield(sim_model, 'flap_model_id')
    model_id = sim_model.flap_model_id;
    return;
end

flap_model = "blade";
if isfield(sim_model, 'flap_model')
    flap_model = lower(string(sim_model.flap_model));
end
switch flap_model
    case "blade"
        model_id = 1;
    case "disk"
        model_id = 2;
    otherwise
        error('VTOL_RESPONSE_STEP:BadFlapModel', ...
            'sim_model.flap_model must be "blade" or "disk".');
end
end

function update_id = response_disk_update_id_step(sim_model)
if isfield(sim_model, 'disk_flap_state_update_id')
    update_id = sim_model.disk_flap_state_update_id;
    return;
end

disk_update = "dynamic";
if isfield(sim_model, 'disk_flap_state_update')
    disk_update = lower(string(sim_model.disk_flap_state_update));
end
switch disk_update
    case "dynamic"
        update_id = 1;
    case "frozen"
        update_id = 2;
    otherwise
        error('VTOL_RESPONSE_STEP:BadDiskFlapStateUpdate', ...
            'sim_model.disk_flap_state_update must be "frozen" or "dynamic".');
end
end

function [errors, forces, beta_vals, dbeta_vals] = response_rotor_force_eval_step(Trim_var, R, Nb, omega, I_beta, velo, k_beta, rotor_profile, theta00, tilt_angle, angular_speed, rotational_direction, acceleration, angular_acc, rotor_bemt_options, Hub_loc, flap_model_id)
switch flap_model_id
    case 1
        [errors, forces, beta_vals, dbeta_vals] = bemt_flapp(Trim_var, R, Nb, omega, I_beta, velo, k_beta, rotor_profile, theta00, tilt_angle, angular_speed, rotational_direction, acceleration, angular_acc, rotor_bemt_options, Hub_loc);
    case 2
        [errors, forces, beta_vals, dbeta_vals] = bemt_flapp_disk(Trim_var, R, Nb, omega, I_beta, velo, k_beta, rotor_profile, theta00, tilt_angle, angular_speed, rotational_direction, acceleration, angular_acc, rotor_bemt_options, Hub_loc);
    otherwise
        error('VTOL_RESPONSE_STEP:BadFlapModel', ...
            'sim_model.flap_model_id must be 1 for blade or 2 for disk.');
end
end

function forces = response_fuselage_forces_step(fixed_controls, velo_body, angular_velocity, sim_model)
if isfield(sim_model, 'fuselage_fun')
    forces = sim_model.fuselage_fun(sim_model.X_CCG, fixed_controls, sim_model.rho, velo_body, angular_velocity, ...
        sim_model.tilt_angle, sim_model.cd, sim_model.cl, sim_model.cm, sim_model.cc, sim_model.cn, sim_model.cll, ...
        sim_model.elev, sim_model.rudd, sim_model.airp, sim_model.fuselage_geometry);
else
    forces = response_default_fuselage_forces_step(sim_model.X_CCG, fixed_controls, sim_model.rho, velo_body, ...
        angular_velocity, sim_model.tilt_angle, sim_model.default_fuselage, sim_model.default_controls, ...
        sim_model.fuselage_geometry);
end
end

function forces = response_default_fuselage_forces_step(X_FUSELAGE_REF, vehicle_control, roe, uvw, pqr, tilt_angle, fuse, ctrl, fuselage_geometry)
S = fuselage_geometry.reference_area_m2;
C_a = fuselage_geometry.mean_aero_chord_m;
b = fuselage_geometry.span_m;

U = uvw(:) + cross(pqr(:), X_FUSELAGE_REF(:));
velocity = sqrt(U(1)^2 + U(2)^2 + U(3)^2);
alpha1 = atan2(U(3), U(1));
alpha = rad2deg(alpha1);
beta1 = atan2(U(2), U(1));
beta = rad2deg(beta1);

cd_cof = fuse.cd0 + 0.*tilt_angle;
cl_cof = fuse.cl_alpha_per_rad * deg2rad(alpha) + 0.*tilt_angle;
cm_cof = fuse.cm_alpha_per_rad * deg2rad(alpha) + 0.*tilt_angle;
cc_cof = fuse.cc_beta + 0.*tilt_angle + 0.*alpha;
cn_cof = fuse.cn_beta + 0.*tilt_angle + 0.*alpha;
cll_cof = fuse.cll_beta + 0.*tilt_angle + 0.*alpha;

elevator_delta = deg2rad(vehicle_control(1)) * ctrl.elevator(:).';
rudder_delta = deg2rad(vehicle_control(2)) * ctrl.rudder(:).';
aileron_delta = deg2rad(vehicle_control(3)) * ctrl.aileron(:).';

dcd = elevator_delta(1);
dcl = elevator_delta(2);
dcm = elevator_delta(3);
dcc_ru = rudder_delta(1);
dcn_ru = rudder_delta(2);
dcll_ru = rudder_delta(3);
dcc_ap = aileron_delta(1);
dcn_ap = aileron_delta(2);
dcll_ap = aileron_delta(3);

dyn_delta = zeros(1,6);
if isfield(fuselage_geometry, 'dynamic_derivatives')
    dyn_delta = fuselage_dynamic_derivative_deltas(U, pqr, velocity, C_a, b, fuselage_geometry.dynamic_derivatives);
end

l = 0.5 * roe * velocity^2 * S * (cl_cof + dcl + dyn_delta(2));
d = 0.5 * roe * velocity^2 * S * (cd_cof + dcd + dyn_delta(1));
m = 0.5 * roe * velocity^2 * S * C_a * (cm_cof + dcm + dyn_delta(3));
c = 0.5 * roe * velocity^2 * S * (cc_cof/5.0*beta + dcc_ru + dcc_ap + dyn_delta(4));
n = 0.5 * roe * velocity^2 * S * b * (cn_cof/5.0*beta + dcn_ru + dcn_ap + dyn_delta(5));
ll = 0.5 * roe * velocity^2 * S * b * (cll_cof/5.0*beta + dcll_ru + dcll_ap + dyn_delta(6));

Fx_wind = [-d; c; -l];
wind2body = [cos(alpha1)*cos(beta1), -cos(alpha1)*sin(beta1), -sin(alpha1);
             sin(beta1),              cos(beta1),               0;
             sin(alpha1)*cos(beta1), -sin(alpha1)*sin(beta1),  cos(alpha1)];
Fx_body = wind2body * Fx_wind;
Moment = cross(X_FUSELAGE_REF, Fx_body');

forces = [Fx_body(1); Fx_body(2); Fx_body(3); ll + Moment(1); m + Moment(2); n + Moment(3)];
end

function [vi_qs, tau_s] = response_uniform_inflow_target_step(forces_body, velo_body, angular_velocity, rotor_tilt_angles, sim_model, rotor_number, vi_current)
tilt = deg2rad(rotor_tilt_angles(rotor_number));
tilt_conversion = [sin(tilt) 0 cos(tilt); 0 1 0; -cos(tilt) 0 sin(tilt)];
force_body = forces_body(1:3);
disc_forces = tilt_conversion * force_body(:);
Tb = disc_forces(3);

hub_loc = sim_model.rotor_locations{rotor_number}(:);
v_hub = velo_body(:) + cross(angular_velocity(:), hub_loc);
v_disc = tilt_conversion * v_hub;
V_inf = v_disc(1);
V_infy = v_disc(2);
V_z = v_disc(3);

vi_qs = response_solve_quasisteady_vi_step(Tb, V_inf, V_infy, V_z, vi_current, sim_model.rho, sim_model.R);
tau_s = response_inflow_tau_s_step(sim_model.rotor_bemt_options, sim_model.omega, sim_model.R, vi_qs);
end

function vi_qs = response_solve_quasisteady_vi_step(Tb, V_inf, V_infy, V_z, vi_initial, rho, R)
area = pi * R^2;
vi = vi_initial;
if ~isfinite(vi)
    vi = 0;
end
for iter = 1:8
    Veff = sqrt((V_z + vi)^2 + V_inf^2 + V_infy^2);
    Veff = max(Veff, 1e-9);
    f = Tb + 2*rho*area*Veff*vi;
    df = 2*rho*area*(Veff + vi*(V_z + vi)/Veff);
    if ~isfinite(f) || ~isfinite(df) || abs(df) < 1e-12
        break;
    end
    step = f / df;
    vi = vi - step;
    if abs(step) < 1e-9
        break;
    end
end
if isfinite(vi)
    vi_qs = vi;
else
    Veff = sqrt((V_z + vi_initial)^2 + V_inf^2 + V_infy^2);
    vi_qs = -Tb / (2*rho*area*max(Veff, 1e-9));
end
end

function model_id = response_inflow_model_id_step(opts)
if isfield(opts, 'inflow_model_id')
    model_id = opts.inflow_model_id;
    return;
end

switch opts.inflow_model
    case "uniform"
        model_id = 1;
    otherwise
        error('VTOL_RESPONSE_STEP:BadInflowModel', 'Unknown inflow model: %s', opts.inflow_model);
end
end

function tau_s = response_inflow_tau_s_step(opts, omega, R, vi_qs)
if isfield(opts, 'inflow_tau_mode_id')
    tau_mode_id = opts.inflow_tau_mode_id;
else
    switch opts.inflow_tau_mode
        case "manual"
            tau_mode_id = 1;
        case "pitt"
            tau_mode_id = 2;
        otherwise
            error('VTOL_RESPONSE_STEP:BadInflowTau', 'Unknown inflow tau mode: %s', opts.inflow_tau_mode);
    end
end

switch tau_mode_id
    case 1
        tau_s = opts.inflow_tau_s;
    case 2
        lambda_eff = max(abs(vi_qs)/(abs(omega)*R), opts.inflow_min_lambda);
        tau_s = 0.849 / (4 * abs(omega) * lambda_eff);
    otherwise
        error('VTOL_RESPONSE_STEP:BadInflowTau', 'Unknown inflow_tau_mode_id.');
end
tau_s = max(tau_s, 1e-6);
end

function [rotor_controls, fixed_controls] = response_effective_control_channels_step(raw_controls, fixed_base, x, rotor_tilt_angles, sim_model)
if ~isfield(sim_model, 'control_blend')
    rotor_controls = raw_controls(:);
    fixed_controls = fixed_base(:);
    return;
end

blend = sim_model.control_blend;
if ~blend.enabled || ~blend.apply_to_response
    rotor_controls = raw_controls(:);
    fixed_controls = fixed_base(:);
    return;
end

tilt_angle_deg = mean(rotor_tilt_angles(:));
speed_mps = sqrt(x(1)^2 + x(2)^2 + x(3)^2);
[rotor_weight, fixed_weight] = response_control_blend_weights_step(speed_mps, tilt_angle_deg, blend);

collective = raw_controls(1);
pitch_cmd = raw_controls(2);
roll_cmd = raw_controls(3);
yaw_cmd = raw_controls(4);

rotor_controls = zeros(4,1);
rotor_controls(1) = collective;
rotor_controls(2) = rotor_weight * blend.rotor_gains(1) * pitch_cmd;
rotor_controls(3) = rotor_weight * blend.rotor_gains(2) * roll_cmd;
rotor_controls(4) = rotor_weight * blend.rotor_gains(3) * yaw_cmd;

fixed_controls = fixed_base(:);
fixed_controls(1) = fixed_controls(1) + fixed_weight * blend.fixed_gains(1) * pitch_cmd;
fixed_controls(3) = fixed_controls(3) + fixed_weight * blend.fixed_gains(2) * roll_cmd;
fixed_controls(2) = fixed_controls(2) + fixed_weight * blend.fixed_gains(3) * yaw_cmd;
end

function [rotor_weight, fixed_weight] = response_control_blend_weights_step(speed_mps, tilt_angle_deg, blend)
switch blend.schedule_id
    case 3
        tilt_min = min(blend.tilt_helicopter_deg, blend.tilt_fixedwing_deg);
        tilt_max = max(blend.tilt_helicopter_deg, blend.tilt_fixedwing_deg);
        tilt_limited = min(max(tilt_angle_deg, tilt_min), tilt_max);
        rotor_weight = min(max(sind(tilt_limited), 0), 1);
        fixed_weight = min(max(cosd(tilt_limited), 0), 1);
        return;
    otherwise
        if blend.independent_variable_id == 2
            s = (tilt_angle_deg - blend.tilt_helicopter_deg) / ...
                (blend.tilt_fixedwing_deg - blend.tilt_helicopter_deg);
        else
            s = (speed_mps - blend.speed_start_mps) / ...
                (blend.speed_end_mps - blend.speed_start_mps);
        end
end
s = min(max(s, 0), 1);
switch blend.schedule_id
    case 1
        fixed_weight = s;
    case 2
        fixed_weight = s*s*(3 - 2*s);
    otherwise
        error('VTOL_RESPONSE_STEP:BadControlBlend', 'Unknown control blend schedule id.');
end
rotor_weight = 1 - fixed_weight;
end

function theta_vec = response_control_allocation_step(rotor_controls)
collective = rotor_controls(1);
longitudinal = rotor_controls(2);
lateral = rotor_controls(3);
yaw = rotor_controls(4);
theta_vec = zeros(1,6);
theta_vec(1) = collective + lateral;
theta_vec(2) = collective + yaw + longitudinal;
theta_vec(3) = collective - yaw + longitudinal;
theta_vec(4) = collective - lateral;
theta_vec(5) = collective - yaw - longitudinal;
theta_vec(6) = collective + yaw - longitudinal;
end

function C_b2e = body_to_earth_matrix_step(phi, theta, psi)
cphi = cos(phi); sphi = sin(phi);
cth = cos(theta); sth = sin(theta);
cpsi = cos(psi); spsi = sin(psi);
C_b2e = [cth*cpsi, sphi*sth*cpsi - cphi*spsi, cphi*sth*cpsi + sphi*spsi;
         cth*spsi, sphi*sth*spsi + cphi*cpsi, cphi*sth*spsi - sphi*cpsi;
         -sth,     sphi*cth,                    cphi*cth];
end
